# include:
include:
  - board: nice_nano_v2
    # shield: v01_left nice_view_adapter nice_view_gem
    shield: v01_left
  - board: nice_nano_v2
    # shield: v01_right nice_view_adapter nice_view_gem
    shield: v01_right
