# include:
include:
  - board: nice_nano_v2
    shield: chocofi_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: chocofi_right nice_view_adapter nice_view_gem chocofi_niceview_cs
